/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void test_add() {
        Library sut = new Library();
        int numOne = 6;
        int numTwo = 2;
        assertEquals(8, sut.add(numOne, numTwo), "addition() yo you need to add more stuff");
    }

    @Test void test_roll() {
        Library sut = new Library();
        System.out.println("roll() Die rolls: " + Arrays.toString(sut.roll(6)));
    }

    @Test void test_containsDuplicates(){
        Library sut = new Library();
        int [] arr = {1,2,3};
        System.out.println("containsDuplicates() Non duplicate array test: " + sut.containsDuplicates(arr));
        assertFalse(sut.containsDuplicates(arr), "roll() Yo you're broke and need to add stuff");
        int [] arrDuplicate = {3,6,8,2,8,7};
        System.out.println("containsDuplicates() Duplicate array test: " + sut.containsDuplicates(arrDuplicate));
        assertTrue(sut.containsDuplicates(arrDuplicate), "roll() Yo you're broke and need to add stuff");

    }

    @Test void test_average(){
        Library sut = new Library();
        double [] arrUno = {1,2,3};
        assertEquals(2, sut.average(arrUno), "average () Yo you're broke and need to add stuff");
        double [] arr2 = {2,3,4,5};
        assertEquals(3, sut.average(arr2), "average () Yo you're broke and need to add stuff");
        double [] arr3 = {3,6,8,2,8,7};
        assertEquals(5, sut.average(arr3), "average () Yo you're broke and need to add stuff");
    }

    @Test void test_arrayOfArrays(){
        Library sut = new Library();
        double[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println("Array of Arrays: " + sut.arrayOfArrays(weeklyMonthTemperatures));
        assertEquals(60.0, sut.arrayOfArrays(weeklyMonthTemperatures), "arrayOfArrays () Yo you're broke and need to add stuff");

    }

}
