/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    @Test void test_newRestaurant() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.newRestaurant(), "Yo you need to look over newRestaurant");
//    }
//
//    @Test void test_newReview() {
//        Library sut = new Library();
//        assertTrue(sut.newReview(), "Yo you need to look over newReview");
//    }
//
//    @Test void test_newShop() {
//        Library sut = new Library();
//        assertTrue(sut.newShop(), "Yo you need to look over newShop");
//    }
//
//    @Test void test_newTheater() {
//        Library sut = new Library();
//        assertTrue(sut.newTheater(), "Yo you need to look over newTheater");
//    }

}
