/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test_linter() {
        App sut = new App();
        try {
            sut.linter("/Users/joshuamccluskey/projects/courses/401/java-fundamentals/linter/app/src/main/resources/gates.js");
        }
        catch (IOException e) {
            System.out.println("Please replace the file path to the absolute path of gates.js on your computer. " +
                    "Example: /Users/joshuamccluskey/projects/courses/401/java-fundamentals/linter/app/src/main/resources/gates.js");
            e.printStackTrace();
        }

    }
}
